name: Publish playlist

on:
  workflow_dispatch:
  schedule:
    - cron:  '58 16 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: 获取当前日期
      id: date
      run: echo "::set-output name=DATE::$(date +'%Y-%m-%d %H:%M:%S')" 
    - name: Generate Playlists
      run: |
        git clone https://LPoImvJTtv:${{ secrets.CODING_TOKEN }}@e.coding.net/wudongdefeng/wudongdefeng/txt-live.git ~/coding
        ls ~/coding/live
        bash ./scripts/generate.sh
        ls ~/coding/live
        git config --global user.name "wudongdefeng"
        git config --global user.email "615563901@qq.com"
        git add .
        git commit -m "init" && echo "exit"
        git push -f https://LPoImvJTtv:${{ secrets.CODING_TOKEN }}@e.coding.net/wudongdefeng/wudongdefeng/txt-live.git
      
